version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - "./hosts:/etc/nginx/conf.d"
            - "./www:/var/www"
            - "./logs:/var/log/nginx"
        links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
        volumes:
            - "./www:/var/www"
    mysql:
        image: mariadb
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: mysql
          MYSQL_USER: mysql
          MYSQL_PASSWORD: mysql
        ports:
            - "3306:3306"
        volumes:
            - "./mysql:/var/lib/mysql/data"